name: 🐛 Relatório de Bug
description: Crie um relatório para nos ajudar a melhorar.
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por dedicar seu tempo para preencher este relatório de bug!

  - type: textarea
    id: o-que-aconteceu
    attributes:
      label: O que aconteceu?
      description: Uma descrição clara e concisa do que é o bug.
    validations:
      required: true

  - type: textarea
    id: passos-para-reproduzir
    attributes:
      label: Passos para Reproduzir
      description: "Como podemos reproduzir o problema? Ex: 1. Vá para '...' 2. Clique em '....' 3. Role para baixo até '....'"
    validations:
      required: true

  - type: dropdown
    id: prioridade
    attributes:
      label: Qual a prioridade?
      options:
        - Baixa
        - Média
        - Alta (Impede o uso de uma funcionalidade)
    validations:
      required: true

  - type: textarea
    id: informacoes-adicionais
    attributes:
      label: Informações Adicionais
      description: "Forneça quaisquer informações adicionais que possam ajudar a resolver o problema."
    validations:
      required: false